import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"
import Header from "./components/header";
import Footer from "./components/footer";
import { Contex } from "./components/Contex";
import { cookies } from "next/headers";
import { prisma } from "@/lib/prisma";



export const metadata: Metadata = {
  title: "yavari polymer",
  description: "Generated by behnam adabzadeh",
};

const vazirmatn = localFont({
  src: "../public/fonts/Vazirmatn-Medium.ttf"
})

// const user = async () => {

//   const data = 

//   return data
// }



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies()
  const session = cookie.get("session")
  // console.log(session);
  let user

  if (session) {
    user = await prisma.users.findUnique({
      where: { id: Number(session.value) },
      select: {
        firstname: true
      }

    })
  }




  return (
    <html
      lang="fa"
      dir="rtl"
      className="h-full antialiased"
    >
      <body className={vazirmatn.className}>
        <Contex initialUser={user?.firstname} >

          {children}
          <Footer />
        </Contex>
      </body>
    </html>
  );
}
