import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"
import Header from "./components/header";
import Footer from "./components/footer";



export const metadata: Metadata = {
  title: "yavari polymer",
  description: "Generated by behnam adabzadeh",
};

const vazirmatn = localFont({
  src : "../public/fonts/Vazirmatn-Medium.ttf"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className= "h-full antialiased"
    >
      <body className={vazirmatn.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
